### ISSUE TITLE
Onboarding packit into jboss-jaxrs-api_spec

### ISSUE THREAD

**Issue by phracek** [jboss/jboss-jaxrs-api_spec#10]
Hi, we would like to onboard `packit` into `jboss-jaxrs-api_spec` upstream repository.

In order to onboard packit to the upstream repository,
we would like to add two files, `packit.yaml` file and Fedora SPEC file.
Is it possible to do it? I will send them over PR.

What do you think about it?

Some brief overview of packit can be found here: https://packit.dev
Especially https://packit.dev/docs/guide/

How does it look like a packit.yaml configuration file? See https://packit.dev/docs/configuration/

Example configuration for jboss-jaxrs-api_spec would be:
```yaml
specfile_path: jboss-jaxrs-2.0-api.spec
synced_files:
   - .packit.yaml
   - jboss-jaxrs-2.0-api.spec
upstream_project_name: jboss-jaxrs-api_spec
downstream_package_name: jboss-jaxrs-2.0-api
jobs:
- job: propose_downstream
  trigger: release
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: f31
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: f30
```

Do you have more jboss packages which can be onboarded by packit?

Once `packit` is onboarded, you can enable GitHub Application `Packit-as-a-Service` (https://github.com/marketplace/packit-as-a-service).
